name: Build Docs and Deploy
on: 
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
jobs:
  build-docs-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Node ğŸµ
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run web:docs
            
      - name: Extract escaped branch name ğŸ£
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//:/g')"
        id: extract_branch

      - name: Install SSH Client ğŸ”‘
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.APIDOC_DEPLOY_KEY }}

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: corona-school/backend-apidocs
          SSH: true
          TARGET_FOLDER: docs/${{ steps.extract_branch.outputs.branch }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: web/public/docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          GIT_CONFIG_NAME: corodoc-bot
